#!/usr/bin/env bash
set -euo pipefail

prompt_file=""
role=""
session=""
while (($#)); do
  case "$1" in
    --prompt-file) prompt_file="$2"; shift 2 ;;
    --role) role="$2"; shift 2 ;;
    --session) session="$2"; shift 2 ;;
    *) echo "unknown harness argument: $1" >&2; exit 64 ;;
  esac
done

test "${LDA_EXECUTION_MODE:-e2b}" = e2b || { echo "LDA refuses non-E2B execution" >&2; exit 78; }
test -s "$prompt_file" || { echo "prompt file is required" >&2; exit 64; }
test -n "$role" && test -n "$session" || { echo "role and session are required" >&2; exit 64; }
role_model_var="LDA_AGENT_MODEL_${role^^}"
selected_model="${!role_model_var:-${LDA_AGENT_MODEL:-}}"
session_dir=/opt/lda/agent-state/sessions
trace_dir=/opt/lda/agent-state/traces
mkdir -p "$session_dir" "$trace_dir"

# A role may pin its own backend (cross-vendor review: Claude builds, Codex
# reviews). Role override first, then the global default, then autodetection.
role_backend_var="LDA_AGENT_BACKEND_${role^^}"
backend="${!role_backend_var:-${LDA_AGENT_BACKEND:-}}"
if test -z "$backend"; then
  if test -n "${ANTHROPIC_API_KEY:-}${ANTHROPIC_AUTH_TOKEN:-}"; then
    backend=claude
  elif test -s /home/user/.codex/auth.json && test "$(wc -c </home/user/.codex/auth.json)" -gt 2; then
    backend=codex
  else
    backend=pi
  fi
fi

if test "$backend" = claude; then
  command -v claude >/dev/null || { echo "claude agent CLI is not installed" >&2; exit 69; }
  thread_file="$session_dir/$session.thread"
  raw_trace="$trace_dir/$session.jsonl"
  turn_file="$trace_dir/$session.turn.jsonl"
  last_message="$session_dir/$session.last.txt"
  model_args=(--model "${selected_model:-claude-opus-4-8}")
  effort_args=(--effort "${LDA_AGENT_THINKING:-high}")
  # stream-json records every event (tool calls included), not just the final
  # result; the per-turn file is appended to the cumulative session trace so
  # no turn overwrites history.
  common_args=(
    --print --bare --verbose --output-format stream-json
    --add-dir /opt/lda/control /opt/lda/skills /opt/lda/humanize
    "${model_args[@]}" "${effort_args[@]}"
  )
  case "$role" in
    analyst|drafter|planner)
      role_args=(--tools Read,Grep,Glob --allowed-tools Read,Grep,Glob --permission-mode dontAsk)
      ;;
    reviewer|supervisor)
      common_args+=(--add-dir /opt/lda/review)
      role_args=(--tools Read,Grep,Glob --allowed-tools Read,Grep,Glob --permission-mode dontAsk)
      ;;
    builder)
      # In-turn mechanical enforcement (Humanize-style validators): the
      # PreToolUse guard blocks evidence tampering during the turn itself.
      role_args=(
        --tools Bash,Edit,Write,Read,Grep,Glob
        --allowed-tools Bash,Edit,Write,Read,Grep,Glob
        --permission-mode dontAsk
        --settings /opt/lda/harness/hooks/builder-settings.json
      )
      ;;
    *) echo "unknown role: $role" >&2; exit 64 ;;
  esac
  # One transient gateway failure must not kill a whole flow round: the turn
  # is retried once with diagnostics. The reply is extracted from THIS
  # turn's stream only -- taking the last result from the cumulative trace
  # would silently replay a previous turn's answer when this one failed.
  # A turn is bounded in wall time (LDA_TURN_TIMEOUT): the relay's own
  # deadline is longer, so a runaway agent process is killed here and never
  # left running behind a relay that already gave up on it.
  turn_timeout="${LDA_TURN_TIMEOUT:-4200}"
  for attempt in 1 2; do
    claude_rc=0
    if test -s "$thread_file"; then
      timeout -k 60 "$turn_timeout" claude "${common_args[@]}" "${role_args[@]}" \
        --resume "$(cat "$thread_file")" "$(cat "$prompt_file")" >"$turn_file" || claude_rc=$?
    else
      timeout -k 60 "$turn_timeout" claude "${common_args[@]}" "${role_args[@]}" \
        "$(cat "$prompt_file")" >"$turn_file" || claude_rc=$?
      thread_id="$(jq -r 'select(.type == "system" and .subtype == "init") | .session_id' "$turn_file" 2>/dev/null | head -1 || true)"
      if test -n "$thread_id" && test "$thread_id" != null; then
        printf '%s\n' "$thread_id" >"$thread_file"
      fi
    fi
    printf '{"kind":"turn_start","role":"%s","session":"%s","attempt":%s,"epoch":%s}\n' \
      "$role" "$session" "$attempt" "$(date +%s)" >>"$raw_trace"
    cat "$turn_file" >>"$raw_trace"
    if test "$claude_rc" = 124; then
      echo "harness: claude turn exceeded LDA_TURN_TIMEOUT=${turn_timeout}s and was killed" >&2
      rm -f "$turn_file"
      exit 124
    fi
    jq -rs '[.[] | select(.type == "result")] | last | .result // empty' "$turn_file" >"$last_message" 2>/dev/null || true
    # A model-gateway failure arrives as a "result" too (the CLI prints the
    # transport error and exits 0). That text is not an answer.
    if test -s "$last_message" && \
       grep -Eq '^API Error|"cloudflare_error": *true|generated by Cloudflare|safeguards flagged this message|Details: `\[cyber\]`' "$last_message"; then
      echo "harness: claude turn returned a model API failure (attempt $attempt):" >&2
      head -c 600 "$last_message" >&2
      echo >&2
      : >"$last_message"
    fi
    if test -s "$last_message"; then
      rm -f "$turn_file"
      cat "$last_message"
      exit 0
    fi
    echo "harness: claude turn produced no result (rc=$claude_rc, attempt $attempt); stream tail:" >&2
    tail -c 700 "$turn_file" >&2 || true
    echo >&2
    rm -f "$turn_file"
    test "$attempt" = 1 && sleep 60
  done
  echo "harness: claude returned no usable result after retries (model gateway failure)" >&2
  exit 75
fi

if test "$backend" = codex; then
  command -v codex >/dev/null || { echo "codex agent CLI is not installed" >&2; exit 69; }
  thread_file="$session_dir/$session.thread"
  raw_trace="$trace_dir/$session.jsonl"
  turn_file="$trace_dir/$session.turn.jsonl"
  last_message="$session_dir/$session.last.txt"
  model_args=()
  test -z "$selected_model" || model_args=(--model "$selected_model")
  provider_args=()
  if test -n "${OPENAI_BASE_URL:-}"; then
    provider_args=(-c "openai_base_url=\"${OPENAI_BASE_URL}\"")
  fi
  # Keep the reasoning budget explicit for Codex runs. The relay sets
  # LDA_AGENT_THINKING=max for this campaign; passing it as a config override
  # prevents a stale sandbox config from downgrading a turn.
  effort_args=(-c "model_reasoning_effort=${LDA_AGENT_THINKING:-high}")
  turn_timeout="${LDA_TURN_TIMEOUT:-4200}"
  codex_rc=0
  if test -s "$thread_file"; then
    thread_id="$(cat "$thread_file")"
    timeout -k 60 "$turn_timeout" codex exec resume --json \
      "${model_args[@]}" "${provider_args[@]}" "${effort_args[@]}" \
      --output-last-message "$last_message" \
      "$thread_id" "$(cat "$prompt_file")" >"$turn_file" 2>&1 || codex_rc=$?
  else
    sandbox_mode=read-only
    test "$role" = builder && sandbox_mode=workspace-write
    timeout -k 60 "$turn_timeout" codex exec --json --sandbox "$sandbox_mode" --cd /opt/lda/work \
      --skip-git-repo-check "${model_args[@]}" "${provider_args[@]}" "${effort_args[@]}" \
      --output-last-message "$last_message" \
      "$(cat "$prompt_file")" >"$turn_file" 2>&1 || codex_rc=$?
    thread_id="$(jq -r 'select(.type == "thread.started") | .thread_id' "$turn_file" 2>/dev/null | head -1 || true)"
    if test -n "$thread_id" && test "$thread_id" != null; then
      printf '%s\n' "$thread_id" >"$thread_file"
    fi
  fi
  printf '{"kind":"turn_start","role":"%s","session":"%s","exit":%s,"epoch":%s}\n' \
    "$role" "$session" "$codex_rc" "$(date +%s)" >>"$raw_trace"
  cat "$turn_file" >>"$raw_trace"
  if test "$codex_rc" -ne 0; then
    echo "harness: Codex turn failed (rc=$codex_rc); trace tail:" >&2
    tail -c 1200 "$turn_file" >&2 || true
    echo >&2
    # Auth, gateway, quota, transport, and timeout failures describe the
    # execution infrastructure, never a package candidate.
    if test "$codex_rc" = 124 || grep -Eqi \
      'unsupported_country|401 Unauthorized|403 Forbidden|429|5[0-9][0-9]|timed? out|connection|transport|rate.?limit|overloaded|API Error' \
      "$turn_file"; then
      rm -f "$turn_file"
      exit 75
    fi
    rm -f "$turn_file"
    exit "$codex_rc"
  fi
  rm -f "$turn_file"
  test -s "$last_message" || {
    echo "harness: Codex turn produced no final message" >&2
    exit 75
  }
  cat "$last_message"
  exit 0
fi

test "$backend" = pi || { echo "unsupported Agent backend: $backend" >&2; exit 64; }
command -v pi >/dev/null || { echo "pi agent CLI is not installed" >&2; exit 69; }

provider_args=()
model_args=()
thinking_args=(--thinking "${LDA_AGENT_THINKING:-high}")
test -z "${LDA_AGENT_PROVIDER:-}" || provider_args=(--provider "$LDA_AGENT_PROVIDER")
test -z "$selected_model" || model_args=(--model "$selected_model")

tool_args=()
case "$role" in
  analyst|reviewer|supervisor) tool_args=(--tools read,grep,find,ls) ;;
  drafter|planner) tool_args=(--tools read,grep,find,ls) ;;
  builder) tool_args=() ;;
  *) echo "unknown role: $role" >&2; exit 64 ;;
esac

prompt=$(cat "$prompt_file")
pi --print --approve \
  --session-id "$session" --session-dir "$session_dir" \
  --skill /opt/lda/skills \
  "${provider_args[@]}" "${model_args[@]}" "${thinking_args[@]}" "${tool_args[@]}" \
  "$prompt"

latest=$(find "$session_dir" -type f -name '*.jsonl' -printf '%T@ %p\n' | sort -nr | head -1 | cut -d' ' -f2-)
test -n "$latest" && cp "$latest" "$trace_dir/$session.jsonl"
