#!/usr/bin/env bash
# Seeded gstreamer1.0-plugins-good fixtures. The Builder sees the default
# (train) directory; the hidden holdout is generated by the host with a
# secret seed into another directory and selected with LDA_GST_FIXDIR.
set -euo pipefail
directory="${LDA_FIXTURE_DIR:-/opt/lda/fixtures/gst}"
seed="${LDA_FIXTURE_SEED:-20260423}"
mkdir -p "$directory" "${LDA_REMOTE_TMPDIR:-/scratch/lda-hm}"
python3 - "$directory" "$seed" <<'PY'
import sys
directory, seed = sys.argv[1], int(sys.argv[2])
state = seed * 2654435761 % 2**31 or 1
def rng(bound):
    global state
    state = (1103515245 * state + 12345) % 2**31
    return state % bound
# Deterministic test-source patterns only (no noise/random patterns).
patterns = ["smpte", "checkers-8", "circular", "gradient", "pinwheel", "spokes", "zone-plate", "ball", "smpte75", "bar"]
waves = ["sine", "square", "saw", "triangle", "ticks", "sine-table", "gaussian-noise"][:6]
flips = ["clockwise", "rotate-180", "counterclockwise", "horizontal-flip", "vertical-flip"]
sizes = [(1280, 720), (1024, 576), (960, 540), (1152, 648)]
w, h = sizes[rng(len(sizes))]
params = {
    "GST_VPATTERN": patterns[rng(len(patterns))],
    "GST_VPATTERN2": patterns[rng(len(patterns))],
    "GST_WIDTH": w, "GST_HEIGHT": h,
    "GST_FLIP": flips[rng(len(flips))],
    "GST_WAVE": waves[rng(len(waves))],
    "GST_FREQ": 220 + rng(1200),
    "GST_FIXTURE_SEED": seed,
}
with open(f"{directory}/params.env", "w", encoding="utf-8") as stream:
    for key, value in params.items():
        stream.write(f"{key}={value}\n")
print("gst fixture params:", params)
PY
# shellcheck disable=SC1090
. "$directory/params.env"
# Container fixtures: raw audio in small blocks inside Matroska and AVI for
# the demux inputs (per-block parsing is the package's code), and a WAV for
# the transcode path.
gst-launch-1.0 -q audiotestsrc wave="$GST_WAVE" freq="$GST_FREQ" num-buffers=9000 samplesperbuffer=512 \
  ! "audio/x-raw,format=S16LE,rate=48000,channels=2" ! matroskamux ! filesink location="$directory/sample-audio.mkv"
gst-launch-1.0 -q audiotestsrc wave="$GST_WAVE" freq="$GST_FREQ" num-buffers=9000 samplesperbuffer=512 \
  ! "audio/x-raw,format=S16LE,rate=48000,channels=2" ! avimux ! filesink location="$directory/sample-audio.avi"
gst-launch-1.0 -q audiotestsrc wave="$GST_WAVE" freq="$GST_FREQ" num-buffers=3000 samplesperbuffer=4096 \
  ! "audio/x-raw,format=S16LE,rate=48000,channels=2" ! wavenc ! filesink location="$directory/sample-audio.wav"
printf 'gst fixtures ready in %s (seed %s)\n' "$directory" "$seed"
